#!/usr/bin/env python3
"""Generate Skyrim quests-data.js and quests-data.json for the static HTML app."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def q(
    id: str,
    name: str,
    category_id: str,
    order: int,
    how_to_start: str,
    description: str,
    *,
    location: str | None = None,
    alternatives: list[str] | None = None,
    can_fail: str | None = None,
    exclusive_group: str | None = None,
    note: str | None = None,
    radiant: bool | None = None,
) -> dict:
    quest: dict = {
        "id": id,
        "name": name,
        "categoryId": category_id,
        "order": order,
        "howToStart": how_to_start,
        "description": description,
    }
    if location is not None:
        quest["location"] = location
    if alternatives is not None:
        quest["alternatives"] = alternatives
    if can_fail is not None:
        quest["canFail"] = can_fail
    if exclusive_group is not None:
        quest["exclusiveGroup"] = exclusive_group
    if note is not None:
        quest["note"] = note
    if radiant is not None:
        quest["radiant"] = radiant
    return quest


CATEGORIES = [
    {
        "id": "main",
        "name": "Main Quest",
        "group": "Main Story",
        "summary": "The Dragonborn prophecy: escape Helgen, learn the Voice, and defeat Alduin.",
    },
    {
        "id": "companions",
        "name": "The Companions",
        "group": "Factions",
        "summary": "Join Whiterun's warrior guild, uncover the beast blood, and decide the Circle's fate.",
    },
    {
        "id": "college",
        "name": "College of Winterhold",
        "group": "Factions",
        "summary": "Study magic at the College, uncover Saarthal's secrets, and save Winterhold from the Eye of Magnus.",
    },
    {
        "id": "thieves_guild",
        "name": "Thieves Guild",
        "group": "Factions",
        "summary": "Restore the Riften underworld, walk Nocturnal's path, and reclaim influence across Skyrim's cities.",
    },
    {
        "id": "dark_brotherhood",
        "name": "Dark Brotherhood",
        "group": "Factions",
        "summary": "Serve Sithis as an assassin—or wipe the Brotherhood out.",
        "exclusiveNote": "Mutually exclusive starts: complete With Friends Like These… to join, or kill Astrid during that quest to begin Destroy the Dark Brotherhood!",
    },
    {
        "id": "imperial",
        "name": "Imperial Legion",
        "group": "Civil War",
        "summary": "Swear to the Empire and reconquer Skyrim for the Legion.",
        "exclusiveNote": "Joining the Legion locks out the Stormcloak campaign (exclusiveGroup: civil-war).",
    },
    {
        "id": "stormcloaks",
        "name": "Stormcloaks",
        "group": "Civil War",
        "summary": "Fight for Ulfric and free Skyrim from Imperial rule.",
        "exclusiveNote": "Joining the Stormcloaks locks out the Imperial campaign (exclusiveGroup: civil-war).",
    },
    {
        "id": "daedric",
        "name": "Daedric Quests",
        "group": "Daedric",
        "summary": "Quests tied to the Daedric Princes and their artifacts.",
    },
    {
        "id": "bards",
        "name": "Bards College",
        "group": "Factions",
        "summary": "Join Solitude's Bards College and recover lost instruments.",
    },
    {
        "id": "dawnguard",
        "name": "Dawnguard",
        "group": "DLC",
        "summary": "Dawnguard DLC: hunt vampires—or join them—and stop Harkon's prophecy.",
        "exclusiveNote": "After Bloodline, choose Dawnguard (dg-hunter) or Volkihar vampires (dg-vampire). Later quests diverge until Kindred Judgment.",
    },
    {
        "id": "dragonborn",
        "name": "Dragonborn",
        "group": "DLC",
        "summary": "Dragonborn DLC: confront Miraak on Solstheim and in Apocrypha.",
    },
    {
        "id": "hearthfire",
        "name": "Hearthfire",
        "group": "DLC",
        "summary": "Hearthfire DLC: buy land, build a homestead, and adopt children.",
    },
    {
        "id": "side_whiterun",
        "name": "Whiterun Hold",
        "group": "Side Quests",
        "summary": "Side quests centered on Whiterun and its hold.",
    },
    {
        "id": "side_riften",
        "name": "The Rift",
        "group": "Side Quests",
        "summary": "Side quests in and around Riften.",
    },
    {
        "id": "side_solitude",
        "name": "Haafingar",
        "group": "Side Quests",
        "summary": "Side quests in Solitude and Haafingar.",
    },
    {
        "id": "side_windhelm",
        "name": "Eastmarch",
        "group": "Side Quests",
        "summary": "Side quests in Windhelm and Eastmarch.",
    },
    {
        "id": "side_markarth",
        "name": "The Reach",
        "group": "Side Quests",
        "summary": "Side quests in Markarth and the Reach.",
    },
    {
        "id": "side_morthal",
        "name": "Hjaalmarch",
        "group": "Side Quests",
        "summary": "Side quests in Morthal and Hjaalmarch.",
    },
    {
        "id": "side_falkreath",
        "name": "Falkreath Hold",
        "group": "Side Quests",
        "summary": "Side quests in Falkreath Hold (non-Daedric).",
    },
    {
        "id": "side_dawnstar",
        "name": "The Pale",
        "group": "Side Quests",
        "summary": "Side quests in Dawnstar and the Pale.",
    },
    {
        "id": "side_winterhold",
        "name": "Winterhold Hold",
        "group": "Side Quests",
        "summary": "Side quests in Winterhold Hold outside the College main line.",
    },
    {
        "id": "side_solstheim",
        "name": "Solstheim",
        "group": "Side Quests",
        "summary": "Dragonborn DLC side quests on Solstheim.",
        "exclusiveNote": "Thirsk Mead Hall: Retaking Thirsk and Chief of Thirsk Hall are mutually exclusive (exclusiveGroup: thirsk-side).",
    },
    {
        "id": "misc_world",
        "name": "Dungeon & World Quests",
        "group": "Side Quests",
        "summary": "Notable dungeon and miscellaneous world quests across Skyrim.",
    },
]


QUESTS: list[dict] = []

# ---------------------------------------------------------------------------
# Main Quest
# ---------------------------------------------------------------------------
QUESTS += [
    q("unbound", "Unbound", "main", 1,
      "Automatic at character creation / Helgen intro.",
      "Escape Helgen during the dragon attack and choose Imperial or Stormcloak escort.",
      location="Helgen",
      alternatives=["Follow Hadvar (Imperial)", "Follow Ralof (Stormcloak)"],
      note="Tutorial; does not lock Civil War faction."),
    q("before-the-storm", "Before the Storm", "main", 2,
      "Continues automatically after Unbound.",
      "Deliver news of the dragon attack to Jarl Balgruuf in Whiterun.",
      location="Riverwood → Whiterun"),
    q("bleak-falls-barrow", "Bleak Falls Barrow", "main", 3,
      "Jarl Balgruuf / Farengar after Before the Storm; also tied to The Golden Claw.",
      "Retrieve the Dragonstone from Bleak Falls Barrow.",
      location="Bleak Falls Barrow"),
    q("dragon-rising", "Dragon Rising", "main", 4,
      "Automatic after returning the Dragonstone.",
      "Help the Whiterun guard defeat Mirmulnir at the Western Watchtower and absorb a dragon soul.",
      location="Western Watchtower"),
    q("way-of-the-voice", "The Way of the Voice", "main", 5,
      "Jarl Balgruuf after Dragon Rising.",
      "Travel to High Hrothgar and meet the Greybeards.",
      location="High Hrothgar"),
    q("horn-of-jurgen-windcaller", "The Horn of Jurgen Windcaller", "main", 6,
      "Greybeards after The Way of the Voice.",
      "Retrieve the Horn from Ustengrav; meet Delphine in Riverwood instead.",
      location="Ustengrav / Sleeping Giant Inn",
      note="Horn is missing; note leads to Delphine."),
    q("blade-in-the-dark", "A Blade in the Dark", "main", 7,
      "Delphine after retrieving her note / Horn quest.",
      "Help Delphine confirm you are Dragonborn by slaying Sahloknir at Kynesgrove.",
      location="Kynesgrove"),
    q("diplomatic-immunity", "Diplomatic Immunity", "main", 8,
      "Delphine after A Blade in the Dark.",
      "Infiltrate the Thalmor Embassy to uncover information about the dragons.",
      location="Thalmor Embassy",
      can_fail="Leaving critical NPCs hostile or missing key dossier can soft-lock progress; follow Delphine's plan."),
    q("cornered-rat", "A Cornered Rat", "main", 9,
      "Delphine after Diplomatic Immunity.",
      "Find Esbern hiding in the Ratway beneath Riften.",
      location="The Ratway, Riften"),
    q("alduins-wall", "Alduin's Wall", "main", 10,
      "Esbern / Delphine after A Cornered Rat.",
      "Escort Esbern to Sky Haven Temple and learn Alduin's history from Alduin's Wall.",
      location="Sky Haven Temple"),
    q("throat-of-the-world", "The Throat of the World", "main", 11,
      "Greybeards after Alduin's Wall (ask about Elder Scroll / Paarthurnax).",
      "Meet Paarthurnax atop the Throat of the World and learn about Dragonrend.",
      location="Throat of the World"),
    q("elder-knowledge", "Elder Knowledge", "main", 12,
      "Paarthurnath / Greybeards / Septimus Signus path.",
      "Recover an Elder Scroll from Blackreach (or via Discerning the Transmundane).",
      location="Alftand / Blackreach / Tower of Mzark",
      note="Overlaps with Discerning the Transmundane."),
    q("alduins-bane", "Alduin's Bane", "main", 13,
      "Automatic after obtaining the Elder Scroll.",
      "Use the Elder Scroll at the Time-Wound, learn Dragonrend, and fight Alduin on the mountain.",
      location="Throat of the World"),
    q("the-fallen", "The Fallen", "main", 14,
      "Continues after Alduin's Bane.",
      "Trap a dragon in Dragonsreach to learn where Alduin fled.",
      location="Dragonsreach, Whiterun",
      note="If Whiterun is contested, Season Unending may be required first."),
    q("season-unending", "Season Unending", "main", 15,
      "Triggered during The Fallen if Civil War is unfinished and Jarl will not allow the trap.",
      "Negotiate a temporary truce at High Hrothgar so Dragonsreach can be used.",
      location="High Hrothgar",
      alternatives=["Concede holds to Empire", "Concede holds to Stormcloaks", "Trade cities via negotiation"],
      note="Optional/conditional; skipped if Civil War already resolved or Whiterun already cooperative."),
    q("paarthurnax-quest", "Paarthurnax", "main", 16,
      "Delphine at Sky Haven Temple after The Throat of the World / Alduin's Wall progress.",
      "Optional Blades demand: kill Paarthurnax for his past crimes.",
      location="Throat of the World",
      alternatives=["Kill Paarthurnax (Blades remain allies)", "Refuse / spare Paarthurnax (Blades refuse further help)"],
      exclusive_group="paarthurnax",
      note="ALT PATH: entirely optional; Greybeards vs Blades loyalty. Does not block Main Quest finale."),
    q("world-eaters-eyrie", "The World-Eater's Eyrie", "main", 17,
      "After learning Alduin's location from the trapped dragon (Odahviing).",
      "Fly to Skuldafn and fight through to Alduin's portal to Sovngarde.",
      location="Skuldafn"),
    q("sovngarde", "Sovngarde", "main", 18,
      "Enter the portal at Skuldafn.",
      "Traverse Sovngarde, clear the mist, and rally the ancient heroes.",
      location="Sovngarde"),
    q("dragonslayer", "Dragonslayer", "main", 19,
      "Continues from Sovngarde.",
      "Defeat Alduin in Sovngarde with the help of Gormlaith, Hakon, and Felldir.",
      location="Sovngarde",
      note="Main Quest finale."),
]

# ---------------------------------------------------------------------------
# Companions
# ---------------------------------------------------------------------------
QUESTS += [
    q("take-up-arms", "Take Up Arms", "companions", 1,
      "Speak to a Companion (often Kodlak or entrants) and ask to join; talk to Skjor/Vilkas.",
      "Join the Companions by proving yourself under Vilkas and Farkas.",
      location="Jorrvaskr, Whiterun"),
    q("proving-honor", "Proving Honor", "companions", 2,
      "Skjor after Take Up Arms and radiant jobs.",
      "Retrieve a fragment of Wuuthrad from Dustman's Cairn with Farkas.",
      location="Dustman's Cairn"),
    q("the-silver-hand", "The Silver Hand", "companions", 3,
      "Skjor after Proving Honor.",
      "Witness the beast blood ritual and assault a Silver Hand hideout with Aela.",
      location="The Underforge / Gallows Rock",
      alternatives=["Accept beast blood", "Skip ritual for now (limits some content until later)"]),
    q("bloods-honor", "Blood's Honor", "companions", 4,
      "Kodlak after further radiants / The Silver Hand.",
      "Retrieve Glenmoril Witch heads for Kodlak's cure research.",
      location="Glenmoril Coven"),
    q("purity-of-revenge", "Purity of Revenge", "companions", 5,
      "Automatic after Kodlak's death following Blood's Honor.",
      "Wipe out the Silver Hand leadership and recover Wuuthrad's fragments.",
      location="Driftshade Refuge"),
    q("glory-of-the-dead", "Glory of the Dead", "companions", 6,
      "Continues after Purity of Revenge.",
      "Enter Ysgramor's Tomb, decide Kodlak's curse, and become Harbinger.",
      location="Ysgramor's Tomb",
      alternatives=["Cure Kodlak's beast blood", "Related choices on your own lycanthropy later via Purity"]),
    # Radiant types
    q("animal-extermination", "Animal Extermination", "companions", 10,
      "Aela the Huntress (radiant).",
      "Clear a beast den threatening locals.",
      radiant=True),
    q("hired-muscle", "Hired Muscle", "companions", 11,
      "Farkas (radiant).",
      "Intimidate a target by brawling them into submission.",
      radiant=True),
    q("trouble-in-skyrim", "Trouble in Skyrim", "companions", 12,
      "Farkas (radiant).",
      "Clear a dungeon of bandits or other hostiles for the Companions.",
      radiant=True),
    q("family-heirloom", "Family Heirloom", "companions", 13,
      "Skjor or Farkas (radiant).",
      "Recover a stolen family heirloom from a dungeon.",
      radiant=True),
    q("escaped-criminal", "Escaped Criminal", "companions", 14,
      "Skjor (radiant).",
      "Track down and kill an escaped criminal.",
      radiant=True),
    q("rescue-mission", "Rescue Mission", "companions", 15,
      "Vilkas (radiant).",
      "Rescue a kidnapping victim from bandits.",
      radiant=True),
    q("striking-the-heart", "Striking the Heart", "companions", 16,
      "Aela (radiant; after The Silver Hand).",
      "Assassinate a Silver Hand leader.",
      radiant=True),
    q("stealing-plans", "Stealing Plans", "companions", 17,
      "Aela (radiant; after The Silver Hand).",
      "Steal Silver Hand plans from a camp.",
      radiant=True),
    q("retrieval", "Retrieval", "companions", 18,
      "Aela (radiant; after The Silver Hand).",
      "Recover a fragment of Wuuthrad from Silver Hand.",
      radiant=True),
    q("totems-of-hircine", "Totems of Hircine", "companions", 19,
      "Aela (radiant; after Glory of the Dead, if still a werewolf).",
      "Recover Totems of Hircine for the Underforge.",
      radiant=True),
    q("purity", "Purity", "companions", 20,
      "Vilkas or Farkas after Glory of the Dead (if they still have beast blood).",
      "Help a Circle member cure their lycanthropy using a Glenmoril head.",
      alternatives=["Cure them", "Decline"],
      radiant=True,
      note="Repeatable for eligible Circle members; uses Glenmoril Witch heads."),
]

# ---------------------------------------------------------------------------
# College of Winterhold
# ---------------------------------------------------------------------------
QUESTS += [
    q("first-lessons", "First Lessons", "college", 1,
      "Speak to Faralda at the College bridge and pass her test (or persuade/Shout).",
      "Gain admission to the College and meet the Arch-Mage and faculty.",
      location="College of Winterhold"),
    q("under-saarthal", "Under Saarthal", "college", 2,
      "Tolfdir after First Lessons.",
      "Explore Saarthal on a student dig and discover the Eye of Magnus.",
      location="Saarthal"),
    q("hitting-the-books", "Hitting the Books", "college", 3,
      "Arch-Mage Savos Aren after Under Saarthal.",
      "Recover stolen books about the Eye from Fellglow Keep.",
      location="Fellglow Keep",
      alternatives=["Free the Orthorn mage", "Leave Orthorn / sacrifice options in dialogue"]),
    q("good-intentions", "Good Intentions", "college", 4,
      "Savos Aren after Hitting the Books.",
      "Consult the Augur of Dunlain in the Midden about the Eye.",
      location="The Midden"),
    q("revealing-the-unseen", "Revealing the Unseen", "college", 5,
      "Mirabelle Ervine after Good Intentions.",
      "Find the Synod's staff research at Mzulft and uncover the Eye's nature.",
      location="Mzulft / Labyrinthian marker"),
    q("containment", "Containment", "college", 6,
      "Automatic after Ancano activates the Eye.",
      "Secure Winterhold after the Eye's surge and deal with the aftermath.",
      location="College of Winterhold / Winterhold"),
    q("staff-of-magnus", "The Staff of Magnus", "college", 7,
      "Continues after Containment.",
      "Retrieve the Staff of Magnus from Labyrinthian.",
      location="Labyrinthian"),
    q("eye-of-magnus", "The Eye of Magnus", "college", 8,
      "Return with the Staff of Magnus.",
      "Defeat Ancano, contain the Eye, and become Arch-Mage.",
      location="College of Winterhold"),
    # Student / faculty sides
    q("arniels-endeavor", "Arniel's Endeavor", "college", 10,
      "Arniel Gane at the College (multi-stage).",
      "Assist Arniel's Dwemer research across several fetch and experiment stages.",
      location="College of Winterhold / various Dwemer ruins",
      note="Multi-part; culminates in a unique summon."),
    q("brelynas-practice", "Brelyna's Practice", "college", 11,
      "Brelyna Maryon after Under Saarthal.",
      "Let Brelyna practice alteration spells on you.",
      location="College of Winterhold"),
    q("jzargos-experiment", "J'zargo's Experiment", "college", 12,
      "J'zargo after Under Saarthal.",
      "Test J'zargo's flame cloaks on undead—carefully.",
      location="Various undead dungeons",
      can_fail="The scrolls can harm you; not a quest failure but easy to die."),
    q("onmunds-request", "Onmund's Request", "college", 13,
      "Onmund after Under Saarthal.",
      "Help Onmund reclaim a family amulet from Enthir.",
      location="College of Winterhold"),
    q("out-of-balance", "Out of Balance", "college", 14,
      "Tolfdir (radiant) after joining.",
      "Cleanse magical disturbances at various locations using Purging Fire.",
      radiant=True),
    q("shalidors-insights", "Shalidor's Insights", "college", 15,
      "Urag gro-Shub (radiant).",
      "Find lost Shalidor writings for the Arcanaeum in exchange for translation perks.",
      radiant=True),
    # Ritual spells
    q("alteration-ritual", "Alteration Ritual Spell", "college", 20,
      "Tolfdir at Alteration 90+.",
      "Fetch heart scales from a dragon and learn Mass Paralysis.",
      location="College of Winterhold"),
    q("conjuration-ritual", "Conjuration Ritual Spell", "college", 21,
      "Phinis Gestor at Conjuration 90+.",
      "Summon and defeat an unbound dremora to obtain Sigil Stone materials; learn Flame Thrall line.",
      location="College of Winterhold"),
    q("destruction-ritual", "Destruction Ritual Spell", "college", 22,
      "Faralda at Destruction 90+.",
      "Complete the elemental tome puzzle at windy peaks; learn Lightning Storm.",
      location="Powerful peak locations across Skyrim"),
    q("illusion-ritual", "Illusion Ritual Spell", "college", 23,
      "Drevis Neloren at Illusion 90+.",
      "Find four master illusion texts with the Vision of the Tenth Eye; learn Harmony.",
      location="College of Winterhold"),
    q("restoration-ritual", "Restoration Ritual Spell", "college", 24,
      "Colette Marence at Restoration 90+; Augur of Dunlain trial.",
      "Survive the Augur's ghostly gauntlet; learn Guardian Circle.",
      location="The Midden"),
]

# ---------------------------------------------------------------------------
# Thieves Guild
# ---------------------------------------------------------------------------
QUESTS += [
    q("chance-arrangement", "A Chance Arrangement", "thieves_guild", 1,
      "Brynjolf in Riften marketplace (or Ratway if missed).",
      "Plant evidence and frame Brand-Shei to prove your skill to Brynjolf.",
      location="Riften",
      can_fail="Failing the distraction still continues, but getting caught has consequences."),
    q("taking-care-of-business", "Taking Care of Business", "thieves_guild", 2,
      "Brynjolf after A Chance Arrangement.",
      "Collect debts from three Riften business owners for the Guild.",
      location="Riften"),
    q("loud-and-clear", "Loud and Clear", "thieves_guild", 3,
      "Brynjolf after Taking Care of Business.",
      "Rob Goldenglow Estate and burn its beehives per Maven's interests.",
      location="Goldenglow Estate",
      alternatives=["Burn enough beehives as instructed", "Extra hostilities if detected"]),
    q("dampened-spirits", "Dampened Spirits", "thieves_guild", 4,
      "Maven Black-Briar / Brynjolf after Loud and Clear.",
      "Sabotage Honningbrew Meadery for Maven.",
      location="Honningbrew Meadery / Whiterun"),
    q("scoundrels-folly", "Scoundrel's Folly", "thieves_guild", 5,
      "Mercer Frey after Dampened Spirits.",
      "Track Gulum-Ei and uncover leads on Karliah.",
      location="Solitude / East Empire Company / Broken Oar Grotto"),
    q("speaking-with-silence", "Speaking With Silence", "thieves_guild", 6,
      "Mercer Frey after Scoundrel's Folly.",
      "Confront Karliah at Snow Veil Sanctum—and learn Mercer betrayed the Guild.",
      location="Snow Veil Sanctum"),
    q("hard-answers", "Hard Answers", "thieves_guild", 7,
      "Karliah after Speaking With Silence.",
      "Translate Gallus's journal via Calcelmo in Markarth.",
      location="Understone Keep / Dwemer Museum / Wizard's Tower"),
    q("the-pursuit", "The Pursuit", "thieves_guild", 8,
      "Karliah / Brynjolf after Hard Answers.",
      "Expose Mercer, infiltrate the Guild vault, and chase leads to irreversible theft.",
      location="Riften / Black-Briar Manor / Guild cistern"),
    q("trinity-restored", "Trinity Restored", "thieves_guild", 9,
      "Karliah after The Pursuit.",
      "Reforge the Nightingale triad at the Twilight Sepulcher pathway.",
      location="Nightingale Hall"),
    q("blindsighted", "Blindsighted", "thieves_guild", 10,
      "Continues after Trinity Restored.",
      "Hunt Mercer Frey in Irkngthand and reclaim the Skeleton Key.",
      location="Irkngthand / Blackreach approach"),
    q("darkness-returns", "Darkness Returns", "thieves_guild", 11,
      "After recovering the Skeleton Key.",
      "Return the Skeleton Key to Nocturnal and walk the Pilgrim's Path.",
      location="Twilight Sepulcher",
      alternatives=["Nightingale Agent", "Nightingale Agent (different boon shrines later)"]),
    q("under-new-management", "Under New Management", "thieves_guild", 12,
      "After Darkness Returns and completing the four city influence quests.",
      "Become Guild Master of the Thieves Guild.",
      location="Riften Ragged Flagon cistern",
      note="Requires Whiterun, Markarth, Windhelm, and Solitude special quests."),
    # City specials
    q("imitation-amnesty", "Imitation Amnesty", "thieves_guild", 20,
      "Delvin Mallory after 5 small jobs in Whiterun Hold (not Riften).",
      "Whiterun city influence quest: forge evidence to free a prisoner for the Guild.",
      location="Whiterun",
      note="City special — unlocks Whiterun merchant / trophy progress."),
    q("silver-lining", "Silver Lining", "thieves_guild", 21,
      "Delvin after 5 small jobs in the Reach.",
      "Markarth city influence quest: recover Endon the silversmith's stolen silver mold.",
      location="Markarth / Pinewatch",
      note="City special."),
    q("summerset-shadows", "Summerset Shadows", "thieves_guild", 22,
      "Delvin after 5 small jobs in Eastmarch.",
      "Windhelm city influence quest: destroy the Summerset Shadows rival guild.",
      location="Windhelm / Uttering Hills Cave",
      note="City special."),
    q("dainty-sload", "The Dainty Sload", "thieves_guild", 23,
      "Delvin after 5 small jobs in Haafingar.",
      "Solitude city influence quest: plant balmora blue on the Dainty Sload.",
      location="Solitude / Dainty Sload",
      note="City special."),
    # Radiant job types
    q("numbers-job", "The Numbers Job", "thieves_guild", 30,
      "Delvin Mallory (radiant).",
      "Alter a business ledger in a hold city.",
      radiant=True),
    q("fishing-job", "The Fishing Job", "thieves_guild", 31,
      "Vex (radiant).",
      "Pickpocket a specific item from a target.",
      radiant=True),
    q("bedlam-job", "The Bedlam Job", "thieves_guild", 32,
      "Delvin Mallory (radiant).",
      "Steal a total value of goods from a hold's city.",
      radiant=True),
    q("shill-job", "The Shill Job", "thieves_guild", 33,
      "Vex (radiant).",
      "Plant stolen goods in a target's home.",
      radiant=True),
    q("sweep-job", "The Sweep Job", "thieves_guild", 34,
      "Vex (radiant).",
      "Steal three specific valuables from a house.",
      radiant=True),
    q("heist-job", "The Heist Job", "thieves_guild", 35,
      "Vex (radiant).",
      "Steal a valuable item from a shop strongbox/safe.",
      radiant=True),
]

# ---------------------------------------------------------------------------
# Dark Brotherhood
# ---------------------------------------------------------------------------
QUESTS += [
    q("delayed-burial", "Delayed Burial", "dark_brotherhood", 1,
      "Cicero on the road near Loreius Farm (White River / Pale area).",
      "Help—or hinder—Cicero with his wagon before he reaches the Dawnstar sanctuary road.",
      location="Loreius Farm",
      alternatives=["Help Cicero (convince Loreius)", "Report Cicero to the guard / side against him"],
      note="Optional lead-in; can complete before or around Innocence Lost."),
    q("innocence-lost", "Innocence Lost", "dark_brotherhood", 2,
      "Hear children rumor in any major city, then speak to Aventus Aretino in Windhelm.",
      "Perform the Black Sacrament's requested killing of Grelod the Kind in Riften.",
      location="Aretino Residence, Windhelm / Honorhall Orphanage, Riften"),
    q("with-friends-like-these", "With Friends Like These…", "dark_brotherhood", 3,
      "Sleep in a bed after Innocence Lost; Astrid abducts you to an abandoned shack.",
      "Kill one of the hostages per Astrid's test to earn an invitation to the Brotherhood.",
      location="Abandoned Shack → Dark Brotherhood Sanctuary",
      alternatives=["Kill a hostage and join", "Kill Astrid instead → starts Destroy the Dark Brotherhood!"],
      exclusive_group="db-start",
      note="ALT PATH: killing Astrid here begins the destroy path and locks the join questline."),
    q("db-sanctuary", "Sanctuary", "dark_brotherhood", 4,
      "Astrid after completing With Friends Like These… (join path).",
      "Meet the family at the Falkreath sanctuary and receive your first contracts from Nazir.",
      location="Dark Brotherhood Sanctuary",
      exclusive_group="db-join"),
    q("db-nazir-contracts", "Nazir's Contract Board", "dark_brotherhood", 5,
      "Nazir at the sanctuary after Sanctuary (and later between story quests).",
      "Complete side assassination contracts assigned by Nazir (Narfi, Ennodius, Beitild, and later targets).",
      location="Various",
      radiant=True,
      exclusive_group="db-join",
      note="Treat as radiant contract set; required early targets gate Mourning Never Comes."),
    q("mourning-never-comes", "Mourning Never Comes", "dark_brotherhood", 6,
      "Astrid after first Nazir contracts.",
      "Assassinate Muiri's targets in Markarth / Lost Knife Hideout area per her Sacrament.",
      location="Markarth / Broken Tower Redoubt",
      exclusive_group="db-join"),
    q("whispers-in-the-dark", "Whispers in the Dark", "dark_brotherhood", 7,
      "Astrid after Mourning Never Comes.",
      "Investigate the Night Mother's coffin and Cicero; become Listener.",
      location="Dark Brotherhood Sanctuary",
      exclusive_group="db-join"),
    q("silence-has-been-broken", "The Silence Has Been Broken", "dark_brotherhood", 8,
      "Night Mother / Astrid after Whispers in the Dark (and more Nazir contracts).",
      "Meet Amaund Motierre in Volunruud and accept the Emperor contract chain.",
      location="Volunruud / Dark Brotherhood Sanctuary",
      exclusive_group="db-join"),
    q("bound-until-death", "Bound Until Death", "dark_brotherhood", 9,
      "Astrid after The Silence Has Been Broken.",
      "Assassinate Vittoria Vici at her wedding in Solitude.",
      location="Solitude",
      exclusive_group="db-join"),
    q("breaching-security", "Breaching Security", "dark_brotherhood", 10,
      "Gabriella after Bound Until Death.",
      "Kill Gaius Maro and plant incriminating evidence on his body.",
      location="Dragon Bridge / travel route",
      alternatives=["Bonus: kill while he is not in Dragon Bridge for extra reward"],
      exclusive_group="db-join"),
    q("cure-for-madness", "The Cure for Madness", "dark_brotherhood", 11,
      "Astrid after Breaching Security.",
      "Track Cicero to the Dawnstar Sanctuary and decide his fate.",
      location="Dawnstar Sanctuary",
      alternatives=["Kill Cicero", "Spare Cicero"],
      exclusive_group="db-join"),
    q("recipe-for-disaster", "Recipe for Disaster", "dark_brotherhood", 12,
      "Astrid / Gourmet subplot after The Cure for Madness.",
      "Assassinate the Gourmet and assume his identity for the Emperor's feast.",
      location="Nightgate Inn",
      exclusive_group="db-join"),
    q("to-kill-an-empire", "To Kill an Empire", "dark_brotherhood", 13,
      "Astrid after Recipe for Disaster.",
      "Infiltrate the Emperor's dinner at Castle Dour as the Gourmet.",
      location="Castle Dour, Solitude",
      exclusive_group="db-join",
      note="The 'Emperor' at the feast is a body double—story continues."),
    q("death-incarnate", "Death Incarnate", "dark_brotherhood", 14,
      "Automatic after To Kill an Empire betrayal.",
      "Escape the Penitus Oculatus raid and burn the Falkreath sanctuary.",
      location="Dark Brotherhood Sanctuary",
      exclusive_group="db-join"),
    q("hail-sithis", "Hail Sithis!", "dark_brotherhood", 15,
      "Night Mother after Death Incarnate.",
      "Confront Motierre, board the Katariah, and assassinate Emperor Titus Mede II.",
      location="The Katariah / Solitude docks",
      alternatives=["Spare or kill Motierre afterward", "Optional: kill Commander Maro"],
      exclusive_group="db-join"),
    q("where-you-hang", "Where You Hang Your Enemy's Head…", "dark_brotherhood", 16,
      "Night Mother after Hail Sithis!.",
      "Refurnish and reopen the Dawnstar Sanctuary as the new home.",
      location="Dawnstar Sanctuary",
      exclusive_group="db-join"),
    q("dark-brotherhood-forever", "The Dark Brotherhood Forever", "dark_brotherhood", 17,
      "Night Mother after Where You Hang Your Enemy's Head….",
      "Repeatable radiant contracts from the Night Mother's new petitioners.",
      radiant=True,
      exclusive_group="db-join"),
    q("destroy-dark-brotherhood", "Destroy the Dark Brotherhood!", "dark_brotherhood", 18,
      "Kill Astrid in the Abandoned Shack during With Friends Like These…, then report to any guard.",
      "Work with Commander Maro to assault and wipe out the Falkreath sanctuary.",
      location="Abandoned Shack → Dark Brotherhood Sanctuary",
      exclusive_group="db-start",
      note="ALT PATH: mutually exclusive with the join questline. Killing Astrid is the trigger."),
]

# ---------------------------------------------------------------------------
# Imperial Legion
# ---------------------------------------------------------------------------
QUESTS += [
    q("joining-the-legion", "Joining the Legion", "imperial", 1,
      "Speak to Legate Rikke / General Tullius in Castle Dour, Solitude (after Unbound).",
      "Swear loyalty to the Empire and clear a fort to enlist.",
      location="Castle Dour, Solitude",
      exclusive_group="civil-war",
      note="Locks out Joining the Stormcloaks."),
    q("jagged-crown-imp", "The Jagged Crown (Imperial)", "imperial", 2,
      "Legate Rikke after Joining the Legion.",
      "Retrieve the Jagged Crown from Korvanjund for the Empire.",
      location="Korvanjund",
      exclusive_group="civil-war-imp",
      alternatives=["Optionally give crown to Stormcloaks instead (switches sides)"]),
    q("message-to-whiterun-imp", "Message to Whiterun (Imperial)", "imperial", 3,
      "Tullius after The Jagged Crown.",
      "Deliver the Legion's demand to Jarl Balgruuf and secure Whiterun's allegiance.",
      location="Whiterun / Solitude",
      exclusive_group="civil-war-imp"),
    q("battle-for-whiterun-imp", "Battle for Whiterun (Imperial)", "imperial", 4,
      "Automatic when Stormcloaks assault Whiterun (Imperial side).",
      "Defend Whiterun from Ulfric's assault.",
      location="Whiterun",
      exclusive_group="civil-war-imp"),
    q("reunification-of-skyrim", "Reunification of Skyrim", "imperial", 5,
      "General Tullius after Battle for Whiterun.",
      "Umbrella campaign quest to reclaim Stormcloak holds for the Empire.",
      location="Skyrim",
      exclusive_group="civil-war-imp",
      note="Parent quest for the following Imperial fort/city battles."),
    q("false-front-imp", "A False Front (Imperial)", "imperial", 6,
      "Legate Rikke during Reunification of Skyrim.",
      "Intercept Stormcloak couriers and forge orders.",
      exclusive_group="civil-war-imp"),
    q("battle-fort-dunstad", "The Battle for Fort Dunstad", "imperial", 7,
      "Legate Rikke during Reunification of Skyrim.",
      "Seize Fort Dunstad in the Pale.",
      location="Fort Dunstad",
      exclusive_group="civil-war-imp"),
    q("compelling-tribute-imp", "Compelling Tribute (Imperial)", "imperial", 8,
      "Legate Rikke during Reunification of Skyrim.",
      "Blackmail/steal a Stormcloak shipment to weaken the Reach resistance.",
      location="Markarth area",
      exclusive_group="civil-war-imp"),
    q("battle-fort-greenwall", "The Battle for Fort Greenwall", "imperial", 9,
      "Legate Rikke during Reunification of Skyrim.",
      "Capture Fort Greenwall in the Rift.",
      location="Fort Greenwall",
      exclusive_group="civil-war-imp"),
    q("rescue-fort-kastav", "Rescue from Fort Kastav", "imperial", 10,
      "Legate Rikke during Reunification of Skyrim.",
      "Rescue Imperial POWs from Fort Kastav.",
      location="Fort Kastav",
      exclusive_group="civil-war-imp"),
    q("battle-fort-amol", "The Battle for Fort Amol", "imperial", 11,
      "Legate Rikke during Reunification of Skyrim.",
      "Take Fort Amol in Eastmarch as a prelude to Windhelm.",
      location="Fort Amol",
      exclusive_group="civil-war-imp"),
    q("battle-for-windhelm", "Battle for Windhelm", "imperial", 12,
      "General Tullius at the end of Reunification of Skyrim.",
      "Assault Windhelm and defeat Ulfric Stormcloak.",
      location="Windhelm",
      exclusive_group="civil-war-imp",
      note="Imperial campaign finale."),
]

# ---------------------------------------------------------------------------
# Stormcloaks
# ---------------------------------------------------------------------------
QUESTS += [
    q("joining-the-stormcloaks", "Joining the Stormcloaks", "stormcloaks", 1,
      "Speak to Ulfric Stormcloak / Galmar in the Palace of the Kings, Windhelm.",
      "Prove yourself to Galmar and swear to the Stormcloak cause.",
      location="Windhelm",
      exclusive_group="civil-war",
      note="Locks out Joining the Legion."),
    q("jagged-crown-sc", "The Jagged Crown (Stormcloak)", "stormcloaks", 2,
      "Galmar Stone-Fist after Joining the Stormcloaks.",
      "Retrieve the Jagged Crown from Korvanjund for Ulfric.",
      location="Korvanjund",
      exclusive_group="civil-war-sc",
      alternatives=["Optionally give crown to the Legion instead (switches sides)"]),
    q("message-to-whiterun-sc", "Message to Whiterun (Stormcloak)", "stormcloaks", 3,
      "Ulfric after The Jagged Crown.",
      "Deliver Ulfric's axe as an ultimatum to Jarl Balgruuf.",
      location="Whiterun / Windhelm",
      exclusive_group="civil-war-sc"),
    q("battle-for-whiterun-sc", "Battle for Whiterun (Stormcloak)", "stormcloaks", 4,
      "Galmar when the assault begins.",
      "Attack Whiterun and force Balgruuf's surrender.",
      location="Whiterun",
      exclusive_group="civil-war-sc"),
    q("liberation-of-skyrim", "Liberation of Skyrim", "stormcloaks", 5,
      "Ulfric after Battle for Whiterun.",
      "Umbrella campaign quest to liberate Imperial holds.",
      location="Skyrim",
      exclusive_group="civil-war-sc",
      note="Parent quest for the following Stormcloak fort/city battles."),
    q("rescue-fort-neugrad", "Rescue from Fort Neugrad", "stormcloaks", 6,
      "Galmar during Liberation of Skyrim.",
      "Rescue Stormcloak prisoners and take Fort Neugrad.",
      location="Fort Neugrad",
      exclusive_group="civil-war-sc"),
    q("compelling-tribute-sc", "Compelling Tribute (Stormcloak)", "stormcloaks", 7,
      "Galmar during Liberation of Skyrim.",
      "Intercept an Imperial tribute caravan tied to Markarth politics.",
      exclusive_group="civil-war-sc"),
    q("battle-fort-sungard", "The Battle for Fort Sungard", "stormcloaks", 8,
      "Galmar during Liberation of Skyrim.",
      "Capture Fort Sungard in the Reach.",
      location="Fort Sungard",
      exclusive_group="civil-war-sc"),
    q("false-front-sc", "A False Front (Stormcloak)", "stormcloaks", 9,
      "Galmar during Liberation of Skyrim.",
      "Kill an Imperial courier and forge military documents.",
      exclusive_group="civil-war-sc"),
    q("battle-fort-snowhawk", "The Battle for Fort Snowhawk", "stormcloaks", 10,
      "Galmar during Liberation of Skyrim.",
      "Seize Fort Snowhawk in Hjaalmarch.",
      location="Fort Snowhawk",
      exclusive_group="civil-war-sc"),
    q("battle-fort-hraggstad", "The Battle for Fort Hraggstad", "stormcloaks", 11,
      "Galmar during Liberation of Skyrim.",
      "Take Fort Hraggstad near Solitude.",
      location="Fort Hraggstad",
      exclusive_group="civil-war-sc"),
    q("battle-for-solitude", "Battle for Solitude", "stormcloaks", 12,
      "Ulfric / Galmar at the end of Liberation of Skyrim.",
      "Assault Castle Dour and kill General Tullius.",
      location="Solitude",
      exclusive_group="civil-war-sc",
      note="Stormcloak campaign finale."),
]

# ---------------------------------------------------------------------------
# Daedric
# ---------------------------------------------------------------------------
QUESTS += [
    q("the-black-star", "The Black Star", "daedric", 1,
      "Speak to Arayna / find Azura's Shrine southeast of Winterhold; talk to Aranea Ienith.",
      "Retrieve Azura's Star from the necromancer Illanil / Malyn Varen's soul experiment.",
      location="Shrine of Azura / Azura's Star interior",
      alternatives=["Purify as Azura's Star (white souls)", "Transform into the Black Star (black souls) with Nelacar"],
      note="ALT PATH: Azura's Star vs Black Star ending."),
    q("boethiahs-calling", "Boethiah's Calling", "daedric", 2,
      "Find Boethiah's Proving (level 30+) or the Sacellum of Boethiah.",
      "Sacrifice a follower, survive Boethiah's tournament, and kill the previous champion.",
      location="Sacellum of Boethiah / Knifepoint Ridge",
      can_fail="Requires a sacrificeable follower; killing the wrong NPCs can complicate setup."),
    q("daedras-best-friend", "A Daedra's Best Friend", "daedric", 3,
      "Speak to Lod in Falkreath about a lost dog, then follow Barbas.",
      "Help Barbas reunite with Clavicus Vile at Haemar's Shame.",
      location="Falkreath / Haemar's Shame",
      alternatives=["Keep the Rueful Axe and kill Barbas", "Return the axe and spare Barbas for the Masque of Clavicus Vile"],
      note="Choice at the end determines artifact."),
    q("discerning-the-transmundane", "Discerning the Transmundane", "daedric", 4,
      "Septimus Signus at his outpost north of Winterhold (also via Elder Knowledge).",
      "Gather blood samples and open a Dwemer lockbox for Septimus—and Hermaeus Mora.",
      location="Septimus Signus's Outpost / Blackreach",
      alternatives=["Oghma Infinium still obtained after Mora's reveal"],
      note="Hermaeus Mora quest; overlaps Main Quest Elder Knowledge."),
    q("ill-met-by-moonlight", "Ill Met By Moonlight", "daedric", 5,
      "Speak to Mathies / Sinding in Falkreath jail about the murdered girl.",
      "Hunt—or aid—the werewolf Sinding under Hircine's eye in Bloated Man's Grotto.",
      location="Falkreath / Bloated Man's Grotto",
      alternatives=["Kill Sinding (Savior's Hide)", "Spare Sinding / kill the hunters (Ring of Hircine)"],
      note="ALT PATH: Savior's Hide vs Ring of Hircine (or both with certain tactics/bugs noted on UESP)."),
    q("the-cursed-tribe", "The Cursed Tribe", "daedric", 6,
      "Discover Largashbur in the Rift and help the orcs under siege.",
      "Lift Malacath's curse by retrieving Shagrol's Warhammer / forging Volendrung.",
      location="Largashbur / Giant's Grove"),
    q("pieces-of-the-past", "Pieces of the Past", "daedric", 7,
      "Read a museum pamphlet or speak to Silus Vesuius at his Dawnstar museum (level 20+).",
      "Recover the pieces of Mehrunes' Razor and decide Silus's fate at the shrine.",
      location="Dawnstar / various ruins / Shrine of Mehrunes Dagon",
      alternatives=["Kill Silus and receive Mehrunes' Razor", "Spare Silus (no razor; museum remains)"],
      note="ALT PATH: Razor requires killing Silus when Dagon demands it."),
    q("the-whispering-door", "The Whispering Door", "daedric", 8,
      "After Dragon Rising, hear Jarl Balgruuf's children rumors; speak to Hulda / Farengar / children (level 20+).",
      "Investigate Mephala's influence on Jarl Balgruuf's children and retrieve the Ebony Blade.",
      location="Dragonsreach, Whiterun"),
    q("the-break-of-dawn", "The Break of Dawn", "daedric", 9,
      "Find Meridia's Beacon in a chest (random) or go to Statue to Meridia west of Solitude.",
      "Cleanse Mount Kilkreath of necromancer Malkoran and claim Dawnbreaker.",
      location="Kilkreath Ruins"),
    q("house-of-horrors", "The House of Horrors", "daedric", 10,
      "Vigilant Tyranus outside an abandoned house in Markarth.",
      "Investigate the house, entrap Logrolf, and decide whether to serve Molag Bal.",
      location="Abandoned House, Markarth",
      alternatives=["Complete Molag Bal's demands for the Mace of Molag Bal", "Refuse further service (quest fails / no artifact)"],
      can_fail="Refusing Molag Bal's commands can fail the quest."),
    q("taste-of-death", "The Taste of Death", "daedric", 11,
      "Speak to Brother Verulus / investigate Hall of the Dead in Markarth; Eola at Reachcliff.",
      "Join Namira's cannibal cult and decide Verulus's fate.",
      location="Markarth / Reachcliff Cave",
      alternatives=["Sacrifice Verulus (Ring of Namira)", "Save Verulus / kill cultists (fail Daedric reward)"],
      can_fail="Killing Eola early or saving Verulus fails the Daedric reward path."),
    q("the-only-cure", "The Only Cure", "daedric", 12,
      "Contract disease and meet a Khajiit messenger, or go to an Afflicted refuge / Peryite's shrine (level 10+).",
      "Inhale Peryite's fumes and kill the renegade cultist Orchendor in Bthardamz.",
      location="Shrine to Peryite / Bthardamz"),
    q("night-to-remember", "A Night to Remember", "daedric", 13,
      "Drink with Sam Guevenne at any inn (level 14+) during a drinking contest.",
      "Reconstruct a lost night of revelry across Skyrim for Sanguine.",
      location="Various (Whiterun start common)",
      note="Reward: Sanguine Rose."),
    q("mind-of-madness", "The Mind of Madness", "daedric", 14,
      "Speak to Dervenin in Solitude about his missing master.",
      "Enter the Pelagius Wing / mindscape and calm Sheogorath's guest.",
      location="Blue Palace, Solitude",
      note="Reward: Wabbajack."),
    q("waking-nightmare", "Waking Nightmare", "daedric", 15,
      "Speak to Erandur at the Windpeak Inn in Dawnstar.",
      "End Dawnstar's nightmares by confronting Vaermina's Skull of Corruption in Nightcaller Temple.",
      location="Dawnstar / Nightcaller Temple",
      alternatives=["Allow Erandur to destroy the Skull", "Kill Erandur and take the Skull of Corruption"],
      note="ALT PATH: keep Erandur as follower-priest vs take Skull of Corruption."),
]

# ---------------------------------------------------------------------------
# Bards College
# ---------------------------------------------------------------------------
QUESTS += [
    q("tending-the-flames", "Tending the Flames", "bards", 1,
      "Speak to Viarmo at the Bards College in Solitude.",
      "Prove King Olaf's verse, convince the court, and gain College membership during the festival.",
      location="Solitude / Dead Men's Respite"),
    q("rjorns-drum", "Rjorn's Drum", "bards", 2,
      "Giraud Gemane after joining the Bards College.",
      "Recover Rjorn's Drum from Halldir's Cairn / related location for teaching bonuses.",
      location="Halldir's Cairn"),
    q("finns-lute", "Finn's Lute", "bards", 3,
      "Inge Six Fingers after joining.",
      "Recover Finn's Lute from Stony Creek Cave / thieves.",
      location="Stony Creek Cave"),
    q("panteas-flute", "Pantea's Flute", "bards", 4,
      "Pantea Ateia after joining.",
      "Recover Pantea's Flute from Hob's Fall Cave.",
      location="Hob's Fall Cave"),
]

# ---------------------------------------------------------------------------
# Dawnguard
# ---------------------------------------------------------------------------
QUESTS += [
    q("dawnguard-join", "Dawnguard", "dawnguard", 1,
      "Hear rumors or go to Fort Dawnguard in the Rift; speak to Isran.",
      "Join the re-formed Dawnguard and investigate Dimhollow Crypt.",
      location="Fort Dawnguard"),
    q("awakening", "Awakening", "dawnguard", 2,
      "Isran after Dawnguard.",
      "Search Dimhollow Crypt and free Serana from her sarcophagus.",
      location="Dimhollow Crypt"),
    q("bloodline", "Bloodline", "dawnguard", 3,
      "Continues after Awakening.",
      "Escort Serana home to Castle Volkihar and choose your allegiance at the gate.",
      location="Castle Volkihar",
      alternatives=["Refuse Harkon's gift → remain with Dawnguard", "Accept Harkon's gift → become Vampire Lord"],
      exclusive_group="dg-faction",
      note="Branch point: dg-hunter vs dg-vampire follow-ups."),
    # Hunter path
    q("a-new-order", "A New Order", "dawnguard", 4,
      "Return to Isran after refusing Harkon (hunter path).",
      "Recruit Florentius, Gunmar, and Sorine to rebuild Fort Dawnguard.",
      location="Fort Dawnguard / various",
      exclusive_group="dg-hunter"),
    q("bloodstone-chalice", "The Bloodstone Chalice", "dawnguard", 5,
      "Lord Harkon after accepting vampirism (vampire path).",
      "Fill the Bloodstone Chalice at Redwater Spring for the Volkihar court.",
      location="Redwater Den / Castle Volkihar",
      exclusive_group="dg-vampire"),
    q("prophet-dg", "Prophet", "dawnguard", 6,
      "Isran (hunter) or Harkon (vampire) after the prior faction quest.",
      "Rescue a Moth Priest and use him to read Serana's Elder Scroll.",
      location="Forebears' Watchtower / Fort Dawnguard or Volkihar",
      note="Exists on both faction paths with location differences."),
    q("seeking-disclosure", "Seeking Disclosure", "dawnguard", 7,
      "After Prophet.",
      "Locate the Elder Scrolls (Sun and Blood) needed for the prophecy.",
      location="Dawnguard HQ or Volkihar",
      note="Often tracked as scroll-hunting objectives tied to Dexion's reading."),
    q("chasing-echoes", "Chasing Echoes", "dawnguard", 8,
      "Serana after obtaining necessary scroll knowledge.",
      "Enter the Soul Cairn via Castle Volkihar's ruined tower to find Valerica.",
      location="Castle Volkihar / Soul Cairn",
      alternatives=["Become a Vampire Lord if still mortal (Serana's offer)", "Soul-trap partial solution with soul gem ritual"]),
    q("beyond-death", "Beyond Death", "dawnguard", 9,
      "Continues in the Soul Cairn.",
      "Help Valerica, battle Durnehviir's keepers, and retrieve the Elder Scroll (Blood).",
      location="Soul Cairn"),
    q("unseen-visions", "Unseen Visions", "dawnguard", 10,
      "After both relevant Elder Scrolls are available.",
      "Perform the Ancestor Glade moth reading to learn the bow's location.",
      location="Ancestor Glade"),
    q("touching-the-sky", "Touching the Sky", "dawnguard", 11,
      "After Unseen Visions.",
      "Retrieve Auriel's Bow from the Forgotten Vale.",
      location="Forgotten Vale / Inner Sanctum"),
    q("kindred-judgment", "Kindred Judgment", "dawnguard", 12,
      "After Touching the Sky.",
      "Lead the final assault on Harkon in the Volkihar cathedral.",
      location="Castle Volkihar",
      note="DLC main finale for both factions."),
    # Major sides / radiants
    q("bolstering-the-ranks", "Bolstering the Ranks", "dawnguard", 20,
      "Isran after A New Order (hunter path).",
      "Find and recruit Florentius Baenius from a hold jail.",
      location="Various jails",
      exclusive_group="dg-hunter"),
    q("ancient-technology", "Ancient Technology", "dawnguard", 21,
      "Sorine Jurard at Fort Dawnguard (radiant).",
      "Recover Dwemer crossbow schematics for the Dawnguard.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("lost-to-the-ages", "Lost to the Ages", "dawnguard", 22,
      "Read The Aetherium Wars or find a Dwemer mechanism / Katria in Arkngthamz.",
      "Compete with Katria's ghost to forge an Aetherial artifact.",
      location="Arkngthamz / Aetherium Forge",
      alternatives=["Aetherial Crown", "Aetherial Shield", "Aetherial Staff"],
      note="Major Dawnguard side quest; forge choice is permanent per character."),
    q("hide-and-seek", "Hide and Seek", "dawnguard", 23,
      "Isran / Dawnguard radiant after main progress.",
      "Find and kill a vampire masquerading among the townsfolk.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("hunting-the-monster", "Hunting the Monster", "dawnguard", 24,
      "Gunmar (radiant).",
      "Track a powerful vampire to a dungeon lair.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("cleansing-light", "Cleansing Light", "dawnguard", 25,
      "Isran (radiant).",
      "Destroy a vampire lair designated by the Dawnguard.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("preemptive-strike", "Preemptive Strike", "dawnguard", 26,
      "Gunmar (radiant).",
      "Assault a cave where vampires threaten a settlement.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("jarls-justice", "A Jarl's Justice", "dawnguard", 27,
      "Isran (radiant).",
      "Expose a vampire visiting a jarl's court.",
      radiant=True,
      exclusive_group="dg-hunter"),
    q("protecting-the-bloodline", "Protecting the Bloodline", "dawnguard", 28,
      "Fura Bloodmouth / Garan Marethi (vampire radiant).",
      "Stop a new vampire hunter cell or destroy Dawnguard assets.",
      radiant=True,
      exclusive_group="dg-vampire"),
    q("culling-the-herd", "Culling the Herd", "dawnguard", 29,
      "Vingalmo (vampire radiant).",
      "Eliminate a designated mortal inconvenience for the court.",
      radiant=True,
      exclusive_group="dg-vampire"),
    q("rings-of-blood-magic", "Rings of Blood Magic", "dawnguard", 30,
      "Feran Sadri after Kindred Judgment (vampire path).",
      "Retrieve valuables to commission powerful vampire rings.",
      exclusive_group="dg-vampire"),
    q("the-hunt", "The Hunt", "dawnguard", 31,
      "Garan Marethi (vampire radiant).",
      "Assassinate a target for the Volkihar clan.",
      radiant=True,
      exclusive_group="dg-vampire"),
    q("deceiving-the-herd", "Deceiving the Herd", "dawnguard", 32,
      "Orthjolf / vampire radiant.",
      "Stage a public vampire scare to manipulate a city.",
      radiant=True,
      exclusive_group="dg-vampire"),
    q("destroying-the-dawnguard", "Destroying the Dawnguard", "dawnguard", 33,
      "Garan Marethi after Kindred Judgment (vampire).",
      "Assault Fort Dawnguard and wipe out the hunters.",
      location="Fort Dawnguard",
      exclusive_group="dg-vampire"),
]

# ---------------------------------------------------------------------------
# Dragonborn main
# ---------------------------------------------------------------------------
QUESTS += [
    q("dragonborn-quest", "Dragonborn", "dragonborn", 1,
      "After Main Quest dragon progress, cultists attack; read their note and travel to Solstheim.",
      "Investigate Miraak's cultists and travel to the Temple of Miraak.",
      location="Windhelm docks → Raven Rock / Temple of Miraak"),
    q("temple-of-miraak", "The Temple of Miraak", "dragonborn", 2,
      "Frea at the Temple of Miraak.",
      "Explore the temple with Frea and free the All-Maker stones' victims temporarily.",
      location="Temple of Miraak"),
    q("fate-of-the-skaal", "The Fate of the Skaal", "dragonborn", 3,
      "Storn Crag-Strider at Skaal Village after The Temple of Miraak.",
      "Cleanse the Wind Stone and learn how Miraak enslaves Solstheim.",
      location="Skaal Village / Wind Stone",
      note="Also listed among Solstheim sides; core to Dragonborn progression."),
    q("path-of-knowledge", "The Path of Knowledge", "dragonborn", 4,
      "Storn / Frea after The Fate of the Skaal.",
      "Recover the Black Book from Nchardak with Neloth's help.",
      location="Nchardak / Tel Mithryn"),
    q("gardener-of-men", "The Gardener of Men", "dragonborn", 5,
      "Read the Black Book: Epistolary Acumen / continue after Path of Knowledge.",
      "Bargain with Hermaeus Mora in Apocrypha; Storn learns Miraak's secret at a cost.",
      location="Apocrypha / Skaal Village"),
    q("summit-of-apocrypha", "At the Summit of Apocrypha", "dragonborn", 6,
      "After The Gardener of Men; use Black Book: Winds of Change / final book path.",
      "Defeat Miraak at the summit of Apocrypha.",
      location="Apocrypha",
      note="Dragonborn DLC finale."),
]

# ---------------------------------------------------------------------------
# Hearthfire
# ---------------------------------------------------------------------------
QUESTS += [
    q("build-your-own-home", "Build Your Own Home", "hearthfire", 1,
      "Become Thane (or friendly enough) and purchase a plot from a steward/jarl in Falkreath, Hjaalmarch, or the Pale.",
      "Buy land and construct a homestead wing by wing with sawn logs, quarried stone, and fittings.",
      location="Lakeview Manor / Windstad Manor / Heljarchen Hall",
      alternatives=["Lakeview Manor (Falkreath)", "Windstad Manor (Hjaalmarch)", "Heljarchen Hall (The Pale)"],
      note="Same quest structure for each plot; can own all three."),
    q("adoption", "Adoption", "hearthfire", 2,
      "Have a house with a child's bed/chest; speak to orphans at Honorhall (after Grelod) or street children.",
      "Adopt up to two children and bring them to a player home.",
      location="Riften Honorhall / various cities / player homes",
      note="Requires Hearthfire housing furniture; Softly Softly / Connie / Blaise / Sofie / Alesan / Lucia etc."),
    q("by-the-book-hf", "Spare Bedroom / Child's Room Setup", "hearthfire", 3,
      "Use the drafting table / carpenter's workbench in a homestead or decorate a city house.",
      "Furnish a child's bedroom to enable adoption in that home.",
      location="Player homes",
      note="Not always a journal quest; tracked here as required Hearthfire setup step."),
]

# ---------------------------------------------------------------------------
# Side: Whiterun
# ---------------------------------------------------------------------------
QUESTS += [
    q("golden-claw", "The Golden Claw", "side_whiterun", 1,
      "Lucan Valerius at Riverwood Trader.",
      "Recover the Golden Claw and the associated claw puzzle from Bleak Falls Barrow.",
      location="Riverwood / Bleak Falls Barrow",
      note="Overlaps Main Quest Bleak Falls Barrow."),
    q("blessings-of-nature", "Blessings of Nature", "side_whiterun", 2,
      "Danica Pure-Spring at the Temple of Kynareth, Whiterun.",
      "Retrieve Nettlebane and sap from the Eldergleam to restore Whiterun's Gildergreen.",
      location="Whiterun / Orphan Rock / Eldergleam Sanctuary",
      alternatives=["Take Eldergleam sap (tree dies temporarily)", "Use Maurice's new sapling instead"]),
    q("in-my-time-of-need", "In My Time of Need", "side_whiterun", 3,
      "Alik'r warriors outside Whiterun or Saadia at the Bannered Mare.",
      "Decide whether Saadia or the Alik'r are telling the truth.",
      location="Whiterun / Swindler's Den",
      alternatives=["Protect Saadia", "Turn Saadia over to Kematu"],
      note="No perfect confirmation in-game; both endings are valid choices."),
    q("missing-in-action", "Missing in Action", "side_whiterun", 4,
      "Fralia Gray-Mane at her stall / Gray-Mane house in Whiterun.",
      "Investigate Thorald Gray-Mane's capture by the Thalmor and rescue him.",
      location="Whiterun / Northwatch Keep",
      alternatives=["Frontal assault on Northwatch", "Imperial missive route if Legion-friendly"]),
]

# ---------------------------------------------------------------------------
# Side: Riften
# ---------------------------------------------------------------------------
QUESTS += [
    q("promises-to-keep", "Promises to Keep", "side_riften", 1,
      "Louis Letrush outside Riften / Black-Briar Lodge leads.",
      "Steal Frost the horse from Black-Briar Lodge for Letrush—or keep it.",
      location="Riften / Black-Briar Lodge",
      alternatives=["Deliver Frost to Letrush", "Keep Frost", "Persuade/extort alternate outcomes"],
      can_fail="Killing key NPCs early can break the quest."),
    q("book-of-love", "The Book of Love", "side_riften", 2,
      "Dinya Balu at the Temple of Mara in Riften.",
      "Play matchmaker across Skyrim for Mara's blessing and the Agent of Mara perk.",
      location="Riften / various holds"),
    q("unfathomable-depths", "Unfathomable Depths", "side_riften", 3,
      "From-Deepest-Fathoms on the Riften docks.",
      "Return a Dwemer lexicon to Avanchnzel and survive the memory-echoes.",
      location="Riften / Avanchnzel"),
]

# ---------------------------------------------------------------------------
# Side: Solitude
# ---------------------------------------------------------------------------
QUESTS += [
    q("lights-out", "Lights Out!", "side_solitude", 1,
      "Jaree-Ra on the Solitude docks.",
      "Extinguish the Solitude lighthouse beacon so pirates can wreck a ship—then deal with the betrayal.",
      location="Solitude Lighthouse / Wreck of the Icerunner / East Empire warehouse caves",
      alternatives=["Go along then wipe out the pirates", "Betray Jaree-Ra earlier"]),
    q("man-who-cried-wolf", "The Man Who Cried Wolf", "side_solitude", 2,
      "Falk Firebeard in the Blue Palace after hearing about Wolfskull Cave.",
      "Investigate necromantic activity in Wolfskull Cave.",
      location="Solitude / Wolfskull Cave"),
    q("wolf-queen-awakened", "The Wolf Queen Awakened", "side_solitude", 3,
      "Letter from Falk Firebeard after The Man Who Cried Wolf (level 10+).",
      "Stop Potema's return in the Solitude catacombs.",
      location="Temple of the Divines / Solitude Catacombs"),
]

# ---------------------------------------------------------------------------
# Side: Windhelm
# ---------------------------------------------------------------------------
QUESTS += [
    q("blood-on-the-ice", "Blood on the Ice", "side_windhelm", 1,
      "Enter Windhelm's graveyard after seeing a murder scene (timing/bug-sensitive).",
      "Investigate the Windhelm serial murders and identify the killer.",
      location="Windhelm / Hjerim",
      alternatives=["Accuse various suspects; correct killer is Calixto"],
      can_fail="Known bugs can soft-lock; follow UESP timing (after visiting market/graveyard correctly)."),
    q("white-phial", "The White Phial", "side_windhelm", 2,
      "Nurelion at The White Phial shop in Windhelm.",
      "Retrieve the White Phial from Forsaken Cave.",
      location="Windhelm / Forsaken Cave"),
    q("repairing-the-phial", "Repairing the Phial", "side_windhelm", 3,
      "Quintus Navale after The White Phial (when Nurelion sickens).",
      "Gather unicorn horn / mammoth tusk powder / soul remnant materials to restore the Phial.",
      location="Windhelm / various"),
    q("rise-in-the-east", "Rise in the East", "side_windhelm", 4,
      "Orthus Endario at the East Empire Company office in Windhelm.",
      "Break the Blood Horker pirates and restore East Empire trade out of Windhelm.",
      location="Windhelm / Dawnstar / Japhet's Folly"),
]

# ---------------------------------------------------------------------------
# Side: Markarth
# ---------------------------------------------------------------------------
QUESTS += [
    q("forsworn-conspiracy", "The Forsworn Conspiracy", "side_markarth", 1,
      "Witness Margret / market attack in Markarth; speak to Eltrys in the shrine of Talos.",
      "Uncover the corrupt conspiracy tying Markarth's leadership to the Forsworn.",
      location="Markarth",
      can_fail="Leaving Markarth at wrong times or killing key NPCs can break the chain."),
    q("cidhna-mine", "No One Escapes Cidhna Mine", "side_markarth", 2,
      "Automatic arrest after The Forsworn Conspiracy.",
      "Survive Cidhna Mine and choose a side to escape.",
      location="Cidhna Mine, Markarth",
      alternatives=["Side with Madanach (Forsworn escape)", "Kill Madanach and escape with Thonar's favor"],
      note="Direct sequel to The Forsworn Conspiracy."),
    q("heart-of-dibella", "The Heart of Dibella", "side_markarth", 3,
      "Speak to a Degaine beggar or visit the Temple of Dibella in Markarth.",
      "Find the next Sybil of Dibella in the countryside and escort her to the temple.",
      location="Markarth / Broken Tower Redoubt area",
      note="Grants Agent of Dibella perk."),
    q("lost-expedition", "The Lost Expedition", "side_markarth", 4,
      "Read expedition notes / speak to Calcelmo or find the dig site under Markarth.",
      "Uncover the fate of the Nimhe / Nchuand-Zel research team and recover their journal.",
      location="Nchuand-Zel, Markarth"),
]

# ---------------------------------------------------------------------------
# Side: Morthal
# ---------------------------------------------------------------------------
QUESTS += [
    q("laid-to-rest", "Laid to Rest", "side_morthal", 1,
      "Speak to the Jarl of Morthal / investigate the burned house rumor.",
      "Uncover a vampire plot and destroy Movarth's lair.",
      location="Morthal / Movarth's Lair"),
    q("rising-at-dawn", "Rising at Dawn", "side_morthal", 2,
      "Ask innkeepers about curing vampirism after becoming a vampire; speak to Falion.",
      "Cure vampirism with Falion's black soul gem ritual at dawn.",
      location="Morthal",
      radiant=True,
      note="Repeatable cure ritual if you become infected again."),
]

# ---------------------------------------------------------------------------
# Side: Falkreath
# ---------------------------------------------------------------------------
QUESTS += [
    q("gather-wheat-falkreath", "Gather Wheat / Chop Wood (Falkreath)", "side_falkreath", 1,
      "Speak to millers and farmers around Falkreath (e.g. half-hold farms and lumber camps).",
      "Repeatable gathering favors typical of Falkreath's rural economy.",
      location="Falkreath Hold",
      radiant=True),
    q("falkreath-bounty-dragon", "Bounty: Kill a Dragon (Falkreath)", "side_falkreath", 2,
      "Jarl or steward of Falkreath after dragons appear.",
      "Radiant dragon bounty for Falkreath Hold.",
      location="Falkreath Hold",
      radiant=True),
    q("falkreath-daedric-pointers", "Lod's Dog / Mathies's Grief", "side_falkreath", 3,
      "Lod (lost dog) or Mathies/Indara at the farm/graves after the child's murder.",
      "Town lead-ins to A Daedra's Best Friend and Ill Met By Moonlight (tracked under Daedric).",
      location="Falkreath",
      note="See Daedric: A Daedra's Best Friend; Ill Met By Moonlight."),
]

# ---------------------------------------------------------------------------
# Side: Dawnstar
# ---------------------------------------------------------------------------
QUESTS += [
    q("dawnstar-museum-lead", "Silus Vesuius's Museum", "side_dawnstar", 1,
      "Read a Mythic Dawn museum pamphlet (level 20+) or visit Silus in Dawnstar.",
      "Opens Pieces of the Past (tracked under Daedric Quests).",
      location="Dawnstar",
      note="See Daedric: Pieces of the Past."),
    q("dawnstar-nightmares-lead", "Windpeak Inn Nightmares", "side_dawnstar", 2,
      "Visit the Windpeak Inn and speak with Erandur / worried locals.",
      "Opens Waking Nightmare (tracked under Daedric Quests).",
      location="Dawnstar",
      note="See Daedric: Waking Nightmare."),
    q("iron-break-mine", "Mine Ore (Iron-Breaker / Quicksilver)", "side_dawnstar", 3,
      "Speak to mine operators in Dawnstar's Iron-Breaker or Quicksilver mines.",
      "Sell ore and clear mine pests; classic Dawnstar livelihood favors.",
      location="Dawnstar mines",
      radiant=True),
]

# ---------------------------------------------------------------------------
# Side: Winterhold
# ---------------------------------------------------------------------------
QUESTS += [
    q("drowned-sorrows", "Drowned Sorrows", "side_winterhold", 1,
      "Speak to Dagur or Haran at the Frozen Hearth about Ranmir's drinking.",
      "Find out what happened to Isabelle and help Ranmir move on.",
      location="Winterhold / Hob's Fall Cave"),
    q("forgotten-names", "Forgotten Names", "side_winterhold", 2,
      "Read manuals near the Atronach Forge in the Midden under the College.",
      "Unlock Atronach Forge recipes, including forbidden Daedric ones.",
      location="The Midden Dark"),
]

# ---------------------------------------------------------------------------
# Side: Solstheim
# ---------------------------------------------------------------------------
QUESTS += [
    q("march-of-the-dead", "March of the Dead", "side_solstheim", 1,
      "Captain Veleth outside Raven Rock after ash spawn attack.",
      "Trace ash spawn to Fort Frostmoth and stop General Falx Carius.",
      location="Raven Rock / Fort Frostmoth"),
    q("final-descent", "The Final Descent", "side_solstheim", 2,
      "Crescius Caerellius in the Raven Rock mine.",
      "Explore the depths of Bloodskal Barrow / Raven Rock Mine and discover Gratian's fate.",
      location="Raven Rock Mine / Bloodskal Barrow"),
    q("served-cold", "Served Cold", "side_solstheim", 3,
      "Councilor Morvayn / Adril Arano after March of the Dead and Final Descent progress.",
      "Uncover an Ulen conspiracy against House Redoran in Raven Rock.",
      location="Raven Rock / Ashfallow Citadel"),
    q("retaking-thirsk", "Retaking Thirsk", "side_solstheim", 4,
      "Speak to the Nords camped outside Thirsk Mead Hall after rieklings took over.",
      "Help Bujold's group reclaim Thirsk from the rieklings.",
      location="Thirsk Mead Hall",
      exclusive_group="thirsk-side",
      alternatives=["Complete the reclaim ritual / confront Bujold's lie"],
      note="ALT PATH: mutually exclusive with Chief of Thirsk Hall."),
    q("chief-of-thirsk", "Chief of Thirsk Hall", "side_solstheim", 5,
      "Speak to the riekling chief inside Thirsk Mead Hall.",
      "Side with the rieklings, complete their tasks, and become their chief.",
      location="Thirsk Mead Hall",
      exclusive_group="thirsk-side",
      note="ALT PATH: mutually exclusive with Retaking Thirsk."),
    q("new-source-of-stalhrim", "A New Source of Stalhrim", "side_solstheim", 6,
      "Deor Woodcutter / Baldor Iron-Shaper missing from Skaal Village.",
      "Rescue Baldor and secure a stalhrim source from the Thalmor.",
      location="Skaal Village / Northshore Landing / Ansilvund-like cave on Solstheim"),
    q("lost-legacy", "Lost Legacy", "side_solstheim", 7,
      "Tharstan in Skaal Village after main Skaal events.",
      "Explore Vahlok's Tomb with Tharstan and learn of the dragon priest Vahlok.",
      location="Vahlok's Tomb"),
    q("cleansing-the-stones", "Cleansing the Stones", "side_solstheim", 8,
      "Storn after The Fate of the Skaal.",
      "Use the Bend Will shout to cleanse the remaining All-Maker Stones.",
      location="Solstheim All-Maker Stones",
      note="Follow-up to Fate of the Skaal / Dragonborn main."),
    q("reluctant-steward", "Reluctant Steward", "side_solstheim", 9,
      "Neloth at Tel Mithryn after arriving on Solstheim.",
      "Find Neloth a new steward in Raven Rock.",
      location="Tel Mithryn / Raven Rock"),
    q("from-the-ashes", "From the Ashes", "side_solstheim", 10,
      "After an ash spawn attack on Tel Mithryn (related to Heart Stone).",
      "Investigate and stop the ash guardian threat tied to Talvas/Neloth's apprentice work.",
      location="Tel Mithryn"),
    q("healing-a-house", "Healing a House", "side_solstheim", 11,
      "Neloth when Tel Mithryn's tower sickens.",
      "Recover a steed / heart stone related cure elements and restore the tower.",
      location="Tel Mithryn / nearby ashen areas"),
    q("old-friends", "Old Friends", "side_solstheim", 12,
      "Neloth during Tel Mithryn quest chain.",
      "Investigate a former apprentice's tower and defeat a dragon priest threat.",
      location="Tel Mithryn / Highpoint Tower"),
    q("wind-and-sand", "Wind and Sand", "side_solstheim", 13,
      "Drop off / purchase related book; or Neloth dialogue about spells.",
      "Bring Neloth research materials related to ash and sand magic.",
      location="Tel Mithryn"),
    q("experimental-subject", "Experimental Subject", "side_solstheim", 14,
      "Neloth at Tel Mithryn.",
      "Allow Neloth to perform a magical experiment on you.",
      location="Tel Mithryn",
      alternatives=["Endure the experiment", "Refuse"]),
    q("telvanni-research", "Telvanni Research", "side_solstheim", 15,
      "Neloth at Tel Mithryn (radiant).",
      "Fetch research materials from dungeons for Neloth's experiments.",
      radiant=True),
    q("lost-knowledge-db", "Lost Knowledge", "side_solstheim", 16,
      "Read a Black Book or speak to Neloth about additional Black Books.",
      "Locate additional Black Books across Solstheim for Apocrypha powers.",
      location="Solstheim / Apocrypha",
      note="Collectible Black Book side content tied to Dragonborn."),
]

# ---------------------------------------------------------------------------
# Misc dungeon & world
# ---------------------------------------------------------------------------
QUESTS += [
    q("forbidden-legend", "Forbidden Legend", "misc_world", 1,
      "Read Lost Legends / find a Gauldur writ; investigate Folgunthur, Geirmund's Hall, and Saarthal.",
      "Defeat the Gauldurson brothers and reforge the Gauldur Amulet.",
      location="Folgunthur / Geirmund's Hall / Saarthal / Reachwater Rock"),
    q("frostflow-abyss", "Frostflow Abyss", "misc_world", 2,
      "Enter Frostflow Lighthouse and read the journal.",
      "Discover the fate of the lighthouse family and purge the chaurus nest below.",
      location="Frostflow Lighthouse"),
    q("the-pale-lady", "The Pale Lady", "misc_world", 3,
      "Enter Frostmere Crypt; overhear/bandit quest about a stolen sword.",
      "Resolve the conflict over the Pale Blade and the Pale Lady's wrath.",
      location="Frostmere Crypt",
      alternatives=["Take the Pale Blade", "Return the Pale Blade to the pedestal"]),
    q("ancestral-worship", "Ancestral Worship", "misc_world", 4,
      "Golldir outside Hillgrund's Tomb.",
      "Help Golldir purge a necromancer from his family's tomb.",
      location="Hillgrund's Tomb"),
    q("silenced-tongues", "Silenced Tongues", "misc_world", 5,
      "Find Heddic's journal in Volunruud.",
      "Explore Volunruud, defeat Elder Kvenel, and claim the Eduj/Okin weapons.",
      location="Volunruud"),
    q("a-scroll-for-anska", "A Scroll for Anska", "misc_world", 6,
      "Anska inside High Peak / Vokun's tomb entrance (High Gate Ruins).",
      "Help Anska retrieve a scroll from Vokun's dragon priest lair.",
      location="High Gate Ruins"),
    q("impatience-of-a-saint", "Impatience of a Saint", "misc_world", 7,
      "Find a page of Saint Jiub's Opus in the Soul Cairn (Dawnguard).",
      "Recover all pages for Jiub and receive his annotated opus / unique jewel.",
      location="Soul Cairn"),
    q("repentance", "Repentance", "misc_world", 8,
      "Illia outside Darklight Tower.",
      "Help Illia stop her mother's hagraven ritual atop Darklight Tower.",
      location="Darklight Tower"),
    q("yngol-barrow", "Yngol Barrow", "misc_world", 9,
      "Enter Yngol Barrow on the coast near Windhelm; optionally with the Coral Dragon Claw from Winterhold.",
      "Solve the barrow puzzle and face Yngol's shade for the Helm of Yngol.",
      location="Yngol Barrow"),
    q("evil-in-waiting", "Evil in Waiting", "misc_world", 11,
      "Enter Valthume; speak to the spirit Valdar.",
      "Gather vessels and defeat Hevnoraak before he rises.",
      location="Valthume"),
    q("melka-and-petra", "The Blind Cliff Bastion", "misc_world", 12,
      "Free Melka in Blind Cliff Cave.",
      "Help the hagraven Melka kill Petra and receive the Staff of Hag's Wrath.",
      location="Blind Cliff Cave"),
    q("infiltration-karthwasten", "Infiltration", "misc_world", 13,
      "Speak to Ainethach in Karthwasten about Silver-Blood thugs at Sanuarach Mine.",
      "Resolve the mine takeover by force or persuasion.",
      location="Karthwasten",
      alternatives=["Drive out the Silver-Bloods", "Side with the enforcers"]),
    q("the-black-books-misc", "Black Book Discoveries", "misc_world", 14,
      "Find Black Books in Solstheim dungeons during exploration.",
      "Enter Apocrypha chapters for standing-stone-like power choices.",
      location="Solstheim / Apocrypha",
      note="Pairs with Dragonborn Lost Knowledge."),
    q("angarvunde", "Angarvunde", "misc_world", 15,
      "Medresi Dran at Angarvunde.",
      "Help Medresi open the ruins; survive the trap and claim the treasure.",
      location="Angarvunde"),
]

# Strengthen hold coverage with additional named UESP-style sides / radiants
EXTRA = [
    q("bounty-falkreath", "Bounty: Kill Bandit Leader (Falkreath)", "side_falkreath", 4,
      "Read a hold bounty or speak to the Falkreath steward/jarl.",
      "Radiant bounty to clear a bandit leader in Falkreath Hold.",
      location="Falkreath Hold",
      radiant=True),
    q("bounty-dawnstar", "Bounty: Kill Bandit Leader (The Pale)", "side_dawnstar", 4,
      "Bounty letter or steward in Dawnstar.",
      "Radiant bounty targeting a bandit leader in the Pale.",
      location="The Pale",
      radiant=True),
    q("bounty-winterhold", "Bounty: Winterhold Hold", "side_winterhold", 3,
      "Jarl / steward of Winterhold bounty letters.",
      "Radiant bounty quests issued from Winterhold.",
      location="Winterhold Hold",
      radiant=True),
    q("fetch-me-that-book", "Fetch Me That Book!", "side_winterhold", 4,
      "Urag gro-Shub in the Arcanaeum.",
      "Find a specific rare book for the College library.",
      location="College of Winterhold",
      radiant=True),
    q("salt-for-arcadia", "Rare Gifts", "side_whiterun", 5,
      "Arcadia at Arcadia's Cauldron (and similar favor NPCs).",
      "Bring a requested rare ingredient or gift item to a citizen.",
      location="Whiterun",
      radiant=True),
    q("caught-red-handed", "Caught Red Handed", "side_riften", 4,
      "Svana at Haelga's Bunkhouse in Riften.",
      "Collect Haelga's Marks of Dibella from her lovers.",
      location="Riften"),
    q("the-raid", "The Raid", "side_riften", 5,
      "Wesply / Sarthis-related Riften warehouse crime (after talking to the jarl's steward about skooma).",
      "Raid a skooma depot tied to Riften's underground trade.",
      location="Riften"),
    q("supply-and-demand", "Supply and Demand", "side_riften", 6,
      "Continues from The Raid / jarl's crime concerns.",
      "Shut down the skooma operation's source outside the city.",
      location="Riften / surrounding caves"),
    q("the-bonds-of-matrimony", "The Bonds of Matrimony", "misc_world", 16,
      "Wear an Amulet of Mara and speak to an interested NPC; arrange the ceremony at the Temple of Mara.",
      "Court and marry an eligible character.",
      location="Temple of Mara, Riften",
      note="Global marriage quest."),
    q("bounty-solitude", "Bounty: Haafingar", "side_solitude", 4,
      "Steward / bounty notes in Solitude.",
      "Radiant bounty for Haafingar Hold.",
      location="Haafingar",
      radiant=True),
    q("tending-flames-pointer", "Elisif's Tribute", "side_solitude", 5,
      "Jarl Elisif the Fair in the Blue Palace after joining her court / hearing about Torygg.",
      "Place Torygg's war horn at a Shrine of Talos for Elisif.",
      location="Solitude / Shrine of Talos"),
    q("naruina-quest", "Dungeon Delving (Calcelmo)", "side_markarth", 5,
      "Calcelmo in Understone Keep.",
      "Retrieve a specific Dwemer artifact from a ruin for Calcelmo.",
      location="Markarth / Dwemer ruins",
      radiant=True),
    q("skoor-the-blood", "Skilled Apprenticeship / Delivery (Markarth)", "side_markarth", 6,
      "Ghorza gra-Bagol or other Markarth crafters.",
      "Miscellaneous crafting apprenticeship and delivery favors in Markarth.",
      location="Markarth"),
]
QUESTS += EXTRA


def validate(data: dict) -> None:
    cat_ids = [c["id"] for c in data["categories"]]
    required = [
        "main", "companions", "college", "thieves_guild", "dark_brotherhood",
        "imperial", "stormcloaks", "daedric", "bards", "dawnguard", "dragonborn",
        "hearthfire", "side_whiterun", "side_riften", "side_solitude", "side_windhelm",
        "side_markarth", "side_morthal", "side_falkreath", "side_dawnstar",
        "side_winterhold", "side_solstheim", "misc_world",
    ]
    if cat_ids != required:
        missing = [c for c in required if c not in cat_ids]
        extra = [c for c in cat_ids if c not in required]
        order_ok = cat_ids == required
        raise SystemExit(f"Category list mismatch. missing={missing} extra={extra} order_ok={order_ok}")

    quest_ids = [x["id"] for x in data["quests"]]
    if len(quest_ids) != len(set(quest_ids)):
        seen = set()
        dupes = []
        for i in quest_ids:
            if i in seen:
                dupes.append(i)
            seen.add(i)
        raise SystemExit(f"Duplicate quest ids: {dupes}")

    for quest in data["quests"]:
        if quest["categoryId"] not in cat_ids:
            raise SystemExit(f"Quest {quest['id']} has unknown category {quest['categoryId']}")


def main() -> None:
    data = {"categories": CATEGORIES, "quests": QUESTS}
    validate(data)

    json_path = ROOT / "quests-data.json"
    js_path = ROOT / "quests-data.js"

    json_text = json.dumps(data, indent=2, ensure_ascii=False)
    json_path.write_text(json_text + "\n", encoding="utf-8")
    js_path.write_text(
        "window.QUESTS_DATA = " + json_text + ";\n",
        encoding="utf-8",
    )

    # Stats
    from collections import Counter

    counts = Counter(q["categoryId"] for q in QUESTS)
    thin = [cid for cid in cat_ids_ordered() if counts[cid] < 2]

    print(f"categories: {len(CATEGORIES)}")
    print(f"quests: {len(QUESTS)}")
    print(f"categories_with_fewer_than_2_quests: {thin if thin else 'none'}")
    for cid in cat_ids_ordered():
        print(f"  {cid}: {counts[cid]}")


def cat_ids_ordered() -> list[str]:
    return [c["id"] for c in CATEGORIES]


if __name__ == "__main__":
    main()
